@startuml
actor "Владелец кошек" as User
participant "Приложение" as App

User -> App: Запуск приложения
App -> User: Система отображает ленту новостей
User -> App: Владелец кошек нажимает кнопку на "Главное меню"
App -> User: Система отображает меню приложения
User -> App: Владелец кошек нажимает на кнопку "Profile"
App -> User: Системы отображает профиль авторизованного пользователя
User -> App: Владелец кошек нажимает иконку фото профиля
App -> User: Система переводит пользователя на экран добавить фото профиля
alt Отмена фото профиль
User -> App: Владелец кошек нажимает на кнопку выбрать из галереии
App -> User: Система переводит пользователя на выбор фото из галереии
User -> App: Владелец кошек выбирает фото для загрузки
App -> User: Система валидирует фото
App -> User: Система система возвращает пользователя на экран с добавленым фото
User -> App: Владелец кошек нажимает на кнопку "Cancel photo"
App -> User: Система отвечает загрузка отменена
App -> User: Система возвращает пользователя на экран профиля
end
alt Ошибка валидации профиль
User -> App: Владелец кошек нажимает на кнопку выбрать из галереии
App -> User: Система переводит пользователя на выбор фото из галереии
User -> App: Владелец кошек выбирает фото для загрузки
App -> User: Система валидирует фото
App -> User: Система система отображает ошибку валидации
User -> App: Система возвращает пользователя на экран добавить фото профиля
end
App -> User: Система переводит пользователя на камеру мобильного устройства
User -> App: Владелец кошек делает фото
App -> User: Система валидирует фото
App -> User: Система возвращает пользователя на экран с добавленым фото
App -> User: Владелец кошек нажимает на кнопку "Download photo"
App -> User: Система отвечает фото загружено
App -> User: Система переводит пользователя на экран профиля
@enduml