@startuml
actor "Владелец кошек" as User
participant "Приложение" as App

User -> App: Запуск приложения
App -> User: Отображение ленты новостей
User -> App: Владелец кошек нажимает на кнопку "Follow"
App -> User: Система регистрирует подписку владельца кошек
User-> App:  Система отображает чек-бокс,что вы теперь подписаны на другого пользователя
alt
User -> App: Запуск приложения
App -> User: Отображение ленты новостей
User -> App: Владелец кошек переходит в профиль другого пользователя через ленту
App -> User: Система отображает профиль другого пользователя
User-> App:  Владелец кошек нажимает на кнопку "Follow"
App-> User:  Система отображает чек-бокс,что вы теперь подписаны на другого пользователя
end
@enduml