@startuml
actor "Владелец кошек" as User
participant "Приложение" as App

User -> App: Запуск приложения
App -> User: Отображение ленты новостей
User -> App: Владелец кошек нажимает на кнопку "Лайк" под фотографией
App -> User: Система регистрирует лайк владельца кошек и обновляет количество лайков фотографии
App-> User: Система отображает обновленное количество лайков фотографии
User-> App: Обновить количество лайков фотографии
App -> User: Система обновляет количество лайков фотографии, уменьшая его на 1
App-> User: Система отображает обновленное количество лайков фотографии
@enduml