@startuml
actor "Владелец кошек" as User
participant "Приложение" as App

User -> App: Запуск приложения
App -> User: Отображение ленты новостей
User -> App: Нажатие кнопку на главное меню
App -> User: Отображение меню приложения
User-> App:  Нажатие на кнопку в "Profile"
App-> User:  Отображение профиля авторизованного пользователя
alt Неудачная загрузка ленты профиля
App-> User: Отображение сообщения об ошибке
User -> App: Прокрутка страницы профиля
App-> User:  Отображение профиля авторизованного пользователя
end
@enduml