@startuml
actor "Владелец кошек" as User
participant "Приложение" as App

User -> App: Запуск приложения
App -> User: Отображение ленты новостей
User -> App: Нажатие на кнопку "Поиск"
App -> User: Система отображает меню поиска
User-> App:  Владелец кошек вводит тег по которому будет искать фото
App-> User:  Система отображает фото с такими тегами
alt Неудачная загрузка поиска
App-> User:  Система отображает сообщения об ошибке
User-> App:  Владелец кошек прокручивает страницу профиля
App-> User:  Система отображает фото с такими тегами
end
@enduml