@startuml
start
:Запустить приложение;
#green: Показать экран ленты публикация;
note right
Экран отображает:
Возможность перейти в личный профиль;
Кнопку поиска;
Публикацию пользователей;
- Имя и дату опубликовавшего пост
- Фото публикации
- Счетчики лайков и комментарий к посту
end note
:Нажать иконку комментариев;
#green: Показать экран комментариев;
note right
Экран отображает:
Стрелку назад к ленте публикаций;
Публикацию пользователя;
- Фото личного профиля опубликовавшего пост
- Имя и дату опубликовавшего пост
- Фото публикации
Под публикацией отображаются;
- Фото пользователя добавившего комментарий
- Имя и дата оставившего комментарий
- Текст комментария
Под комментариями отображается;
- Фото вашего профиля
- Полле ввода Add Comments
- Кнопка c воможностью оставить комментарий
end note
:Вернуться к ленте новостей;
#green: Показать экран ленты публикация;
:Перейти в личный профиль;
#green: Показать экран личного профиля;
note right
Экран отображает:
Стрелку назад к ленте публикаций;
Фото личного профиля;
- Имя профиля
- Дату регистрации
- Кнопку Add Post
Под кнопкой Add Post - указаны часто используемые тэги;
Под тегами - счетчик подписчиков, подписок и лайков;
Под счетчиками - Посты пользователя;
- Фото поста
- Теги к посту
end note
:Нажать кнопку Add Photo;
#green: Показать экран загрузки фото;
note right
Экран отображает:
Возможность выбрать фото из галереии;
Возможность сделать фото;
end note
:Выбрать фото из галереии;
#green: Показать экран загруженного фото;
note right
Экран отображает:
Фото которое было загружено
Под фото - возможность добавить описание
Под описание - оставить Теги
По тегами - кнопка publish photo
Под кнопкой publish photo - кнопка Cancel Download
end note
:Нажать кнопку publish photo;
#green: Показать экран личного профиля;
stop 
@enduml