@startuml
skinparam packageStyle rectangle
actor "Владелец питомцев"
rectangle CatsPost {
"Владелец питомцев" --> (Вход в приложение)
(Вход в личный профиль) ....> (Аутентификация) : include
(Вход в личный профиль) ...> (Просмотр опубликованых фото) :include
(Просмотр опубликованых фото) ...> (Удалить фото) :extend
(Вход в личный профиль) ...> (Опубликовать фото) :include
(Опубликовать фото) ...> (Отменить загрузку фото) : extend
(Вход в личный профиль) ...> (Работа с аватаром) :include
(Работа с аватаром) ...> (Добавить фото) :extend
(Работа с аватаром) ...> (Изменить фото) :extend
(Вход в приложение) .> (Регистрация) : extend
(Вход в приложение) .> (Аутентификация) : extend
(Работа с лентой) ..> (Аутентификация) : include
(Работа с лентой) ..> (Работа с лайками) : include
(Работа с лентой) ..> (Перейти в профиль другого пользователя) : include
(Перейти в профиль другого пользователя) .> (Просмотр опубликованых фото) : include
(Работа с лентой) ....> (Подписаться на другого пользователя) : include
(Работа с лентой) ..> (Поиск другого пользователя) : include
}
@enduml