@startuml
actor "Владелец кошек" as User
box "CatsPost"
    participant "UI" as UI
end box
participant "API-Gateway" as Gateway
box "Catsauth Service"
participant "REST API" as REST
end box
database "database" as db



group Use Case 1: Регистрация нового пользователя
activate User
activate UI
User <- UI:Приложение запрашивает электронную почту и пароль
User <- UI:Приложение запрашивает электронную почту и пароль
User <- User:Владелец кошек вводит e-mail и password
User -> UI:Владелец кошек нажимает кнопку "Сontinue"
activate Gateway
activate REST
UI -> Gateway:Владелец кошек нажимает кнопку "Continue"
Gateway -> REST:Отправить данные на проверку
REST -> REST:Валидация данных
alt Неверные данные
activate db
REST -> db:Проверка введенных данных
REST --> Gateway:Данные невалидны
Gateway --> UI:Данные невалидны
UI --> User:Отображение сообщения об ошибке невалидных данных
end
end group
@enduml