@startuml
actor "Владелец кошек" as User
participant "Приложение" as App

User -> App: Запуск приложения
App -> User: Отображение ленты новостей

alt Неудачная загрузка ленты
  User <-- App: Отображение сообщения об ошибке
else
  User -> App: Прокрутка ленты фотографий
  App -> User: Обновление отображения ленты фотографий
end
@enduml