@startuml
actor "Владелец кошек" as User
box "CatsPost"
    participant "UI" as UI
end box
participant "API-Gateway" as Gateway
box "Catsauth Service"
participant "REST API" as REST
end box



group Use Case 1: Работа с лентой
activate User
activate UI
activate Gateway
activate REST
User -> UI:Владелец кошек запускает мобильное приложение
UI -> Gateway:Владелец кошек запускает мобильное приложение
Gateway -> REST:Владелец кошек запускает мобильное приложение
alt Неудачная загрузка ленты
Gateway <-- REST:Сервис недоступен
UI <-- REST:Сервис недоступен
User <-- UI:Приложение отображает сообщения об ошибке
else Обновление пользователя
User -> UI:Владелец кошек прокручивает экран ленты
UI -> Gateway:Владелец кошек прокручивает экран ленты
Gateway -> REST:Владелец кошек прокручивает экран ленты
Gateway <-- REST:Обновленное отображение ленты новостей
UI <-- REST:Обновленное отображение ленты новостей
User <-- UI:Обновленное отображение ленты новостей
end
User <-- UI:Система отображает ленту новостей
deactivate User
deactivate UI
deactivate Gateway
deactivate REST
end group
@enduml