@startuml
actor "Владелец кошек" as User
box "CatsPost"
    participant "UI" as UI
end box
participant "API-Gateway" as Gateway
box "Catsauth Service"
participant "REST API" as REST
end box



group Use Case 2: Лайк фотографий
activate User
activate UI
activate Gateway
activate REST
User -> UI:Владелец кошек нажимает на кнопку "Like" под фотографией
UI -> Gateway:Владелец кошек нажимает на кнопку "Like" под фотографией
Gateway -> REST:Владелец кошек нажимает на кнопку "Like" под фотографией
alt
else Снять лайк с фото
User -> UI:Обновить количество лайков фотографии
UI -> Gateway:Обновить количество лайков фотографии
Gateway -> REST:Обновить количество лайков фотографии
Gateway <-- REST:Приложение обновляет кол-во лайков фотографии, уменьшая его на 1
UI <-- Gateway:Приложение обновляет кол-во лайков фотографии, уменьшая его на 1
User <-- UI:Приложение отображает обновленное количество лайков фотографии
end
Gateway <-- REST:Приложение обновляет количество лайков фотографии
UI <-- REST:Приложение обновляет количество лайков фотографии
User <-- UI:Приложение отображает обновленное количество лайков фотографии
deactivate User
deactivate UI
deactivate Gateway
deactivate REST
end group
@enduml