@startuml
actor "Владелец кошек" as User
participant "Приложение" as App

User -> App: Запуск приложения
App -> User: Система отображает ленту новостей
User -> App: Владелец кошек нажимает кнопку на "Главное меню"
App -> User: Система отображает меню приложения
User -> App: Владелец кошек нажимает на кнопку "Profile"
App -> User: Системы отображает профиль авторизованного пользователя
User -> App: Владелец кошек нажимает на фото которое нужно удалить
App -> User: Система возвращает экран фото
User -> App: Владелец кошек  нажимает на кнопку "Delete photo"
App -> User: Система отвечает сообщением с предупеждением
User -> App: Владелец кошек отвечает "Yes"
App -> User: Система отвечает фото удалено
alt Ошибка системы при удалении
User -> App: Владелец кошек отвечает "Yes"
App -> User: Система возвращает сообщение об ошибке
App -> User: Система возвращает пользователя на экран удаления фото
end
alt Пользователь нажал No
User -> App: Владелец кошек отвечает "No"
App -> User: Система возвращает пользователя на экран удаления фото
end
App -> User: Система возвращает пользователя на экран профиля
@enduml