@startuml
actor "Пользователь" as User
box "Котограмм"
    participant "UI" as UI
end box
participant "API-Gateway" as Gateway
box "Catsauth Service"
participant "REST API" as REST
end box



group Use Case 1: Регистрация нового пользователя
activate User
activate UI
User -> UI: Пользователь нажимает кнопку "Зарегистрироваться"
User <-- UI: Система отображает форму регистрации
User -> User: Пользователь вводит Nickname, email, password
activate Gateway
activate REST
User -> UI: Пользователь нажимает кнопку "Continue"
UI -> Gateway: Пользователь нажимает кнопку "Continue"
Gateway -> REST: Отправить данные на проверку POST auth/signup
REST -> REST: Валидация данных
alt Неверные данные
REST -> REST: Проверка на уникальность
REST --> Gateway: Ответ с ошибкой User with this email already exists.
Gateway --> UI: Ответ с ошибкой 
UI --> User: Показать данные об ошибке
end
REST -> REST: Сохранить новую учетную запись
REST -> Gateway: Ответ об успешном сохранении пользователя, возвращает JWT токен и refresh_token
Gateway -> UI: Ответ об успешном сохранении пользователя
UI -> User: Ответ об успешном сохранении пользователя
deactivate User
deactivate UI
deactivate Gateway
deactivate REST
end group
@enduml