@startmindmap

* Stakeholders

** Разработчики

*** Mobile developers

*** Back-end developers

** Users

*** Владельцы кошек

*** Любители кошек

*** Сообщество любителей кошек

** Рекламодатели

*** Зоомагазины

*** Ветеринарные клиники

*** Приюты для кошек

*** Бренды кормов для домашних животных

*** Производители товаров для домашних животных

@endmindmap